


all:
	make theme1
	make theme3
	make theme4
	make theme5
	make theme6
	make theme7
	make theme2


theme1:
	cp ../css/geek_theme1.less geek_temp.less
	lessc geek.less > geek_theme1.css
	
	
theme2:
	cp ../css/geek_theme2.less geek_temp.less
	lessc geek.less > geek_theme2.css
	

theme3:
	cp ../css/geek_theme3.less geek_temp.less
	lessc geek.less > geek_theme3.css
	
	
theme4:
	cp ../css/geek_theme4.less geek_temp.less
	lessc geek.less > geek_theme4.css
	
	
theme5:
	cp ../css/geek_theme5.less geek_temp.less
	lessc geek.less > geek_theme5.css
	
	
theme6:
	cp ../css/geek_theme6.less geek_temp.less
	lessc geek.less > geek_theme6.css
		
	
theme7:
	cp ../css/geek_theme7.less geek_temp.less
	lessc geek.less > geek_theme7.css
		
		
theme8:
	cp ../css/geek_theme8.less geek_temp.less
	lessc geek.less > geek_theme8.css
		


terminal-tron:
	cp ../css/terminal_tron.less geek_temp.less
	lessc geek.less > terminal_tron.css
	

terminal-solarized:
	cp ../css/terminal_solarized.less geek_temp.less
	lessc geek.less > terminal_solarized.css
	


minimaxing_theme01:
	cp ../css/minimaxing_theme01.less geek_temp.less
	lessc geek.less > minimaxing_theme01.css


newspaper_theme01:
	cp ../css/newspaper_theme01.less geek_temp.less
	lessc geek.less > newspaper_theme01.css
