apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lionwiki-data
  labels:
    app: lionwiki
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  volumeName: lionwiki-data-pv
  resources:
    requests:
      storage: 500Mi
