apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lionwiki
  labels:
    app: lionwiki
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: yourdomain.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lionwiki
            port:
              number: 80
  tls:
  - hosts:
    - yourdomain.org
    secretName: lionwiki-tls
