apiVersion: v1
kind: PersistentVolume
metadata:
  name: lionwiki-data-pv
  labels:
    app: lionwiki
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/lionwiki-data
    type: DirectoryOrCreate
