


all:
	make theme1
	make theme3
	make theme4
	make theme5
	make theme6
	make theme7
	make theme8
	make theme2


theme1:
	cp ../css/brut_theme1.less brut_temp.less
	lessc brut.less > brut_theme1.css
	
	
theme2:
	cp ../css/brut_theme2.less brut_temp.less
	lessc brut.less > brut_theme2.css
	

theme3:
	cp ../css/brut_theme3.less brut_temp.less
	lessc brut.less > brut_theme3.css
	
	
theme4:
	cp ../css/brut_theme4.less brut_temp.less
	lessc brut.less > brut_theme4.css
	
	
theme5:
	cp ../css/brut_theme5.less brut_temp.less
	lessc brut.less > brut_theme5.css
	
	
theme6:
	cp ../css/brut_theme6.less brut_temp.less
	lessc brut.less > brut_theme6.css
		
	
theme7:
	cp ../css/brut_theme7.less brut_temp.less
	lessc brut.less > brut_theme7.css
		
		
theme8:
	cp ../css/brut_theme8.less brut_temp.less
	lessc brut.less > brut_theme8.css
		


terminal-tron:
	cp ../css/terminal_tron.less brut_temp.less
	lessc brut.less > terminal_tron.css
	

terminal-solarized:
	cp ../css/terminal_solarized.less brut_temp.less
	lessc brut.less > terminal_solarized.css
	


minimaxing_theme01:
	cp ../css/minimaxing_theme01.less brut_temp.less
	lessc brut.less > minimaxing_theme01.css


newspaper_theme01:
	cp ../css/newspaper_theme01.less brut_temp.less
	lessc brut.less > newspaper_theme01.css
