


all:
	make minimaxing_terminal_nord
	make minimaxing_terminal_tron
	make minimaxing_terminal_green
	make minimaxing_terminal_black
	make minimaxing_terminal_white
	make minimaxing_terminal_solarized
	make minimaxing_geek_theme01
	make minimaxing_geek_theme02
	make minimaxing_geek_theme03
	make minimaxing_theme03
	make minimaxing_theme02
	make minimaxing_theme01


minimaxing_theme01:
	cp ../css/minimaxing_theme01.less minimaxing_temp.less
	lessc minimaxing.less > minimaxing_theme01.css



minimaxing_theme02:
	cp ../css/minimaxing_theme02.less minimaxing_temp.less
	lessc minimaxing.less > minimaxing_theme02.css
	
	
minimaxing_theme03:
	cp ../css/minimaxing_theme03.less minimaxing_temp.less
	lessc minimaxing.less > minimaxing_theme03.css
	

minimaxing_terminal_nord:
	cp ../css/terminal_nord.less minimaxing_temp.less
	lessc minimaxing.less > terminal_nord.css
	
	

minimaxing_terminal_tron:
	cp ../css/terminal_tron.less minimaxing_temp.less
	lessc minimaxing.less > terminal_tron.css
	

minimaxing_terminal_green:
	cp ../css/terminal_green.less minimaxing_temp.less
	lessc minimaxing.less > terminal_green.css
	
	
minimaxing_terminal_solarized:
	cp ../css/terminal_solarized.less minimaxing_temp.less
	lessc minimaxing.less > terminal_solarized.css
	


minimaxing_terminal_black:
	cp ../css/terminal_black.less minimaxing_temp.less
	lessc minimaxing.less > terminal_black.css


minimaxing_terminal_white:
	cp ../css/terminal_white.less minimaxing_temp.less
	lessc minimaxing.less > terminal_white.css
	

minimaxing_geek_theme01:
	cp ../css/geek_theme1.less minimaxing_temp.less
	#sed -i 's///g' minimaxing_temp.less
	lessc minimaxing.less > geek_theme1.css
	
minimaxing_geek_theme02:
	cp ../css/geek_theme2.less minimaxing_temp.less
	lessc minimaxing.less > geek_theme1.css

minimaxing_geek_theme03:
	cp ../css/geek_theme3.less minimaxing_temp.less
	lessc minimaxing.less > geek_theme1.css
	
minimaxing_geek_theme04:
	cp ../css/geek_theme4.less minimaxing_temp.less
	lessc minimaxing.less > geek_theme1.css

minimaxing_geek_theme05:
	cp ../css/geek_theme5.less minimaxing_temp.less
	lessc minimaxing.less > geek_theme1.css
	
	
minimaxing_geek_theme06:
	cp ../css/geek_theme6.less minimaxing_temp.less
	lessc minimaxing.less > geek_theme1.css
	
