


all:
	make theme1
	make theme3
	make theme2
	make theme4

theme1:
	cp ../css/lagrange_theme1.less lagrange_temp.less
	lessc lagrange.less > lagrange_theme1.css
	
	
theme2:
	cp ../css/lagrange_theme2.less lagrange_temp.less
	lessc lagrange.less > lagrange_theme2.css
	

theme3:
	cp ../css/lagrange_theme3.less lagrange_temp.less
	lessc lagrange.less > lagrange_theme3.css
	
	
theme4:
	cp ../css/lagrange_theme4.less lagrange_temp.less
	lessc lagrange.less > lagrange_theme4.css
	

