


all:
	make nord
	make tron
	make green
	make black
	make white
	make geek_theme1
	make solarized

	
nord:
	cp ../css/terminal_nord.less terminal_temp.less
	lessc terminal.less > terminal_nord.css
	
	

tron:
	cp ../css/terminal_tron.less terminal_temp.less
	lessc terminal.less > terminal_tron.css
	

green:
	cp ../css/terminal_green.less terminal_temp.less
	lessc terminal.less > terminal_green.css
	
	
solarized:
	cp ../css/terminal_solarized.less terminal_temp.less
	lessc terminal.less > terminal_solarized.css
	


black:
	cp ../css/terminal_black.less terminal_temp.less
	lessc terminal.less > terminal_black.css


white:
	cp ../css/terminal_white.less terminal_temp.less
	lessc terminal.less > terminal_white.css
	

geek_theme1:
	cp ../css/geek_theme1.less terminal_temp.less
	lessc terminal.less > geek_theme1.css
	
