


all:
	make geek_theme07
	make geek_theme06
	make newspaper_theme05
	make newspaper_theme04
	make newspaper_theme03
	make newspaper_theme02
	make newspaper_theme01





newspaper_theme01:
	cp ../css/newspaper_theme01.less newspaper_temp.less
	lessc newspaper.less > newspaper_theme01.css
	

newspaper_theme02:
	cp ../css/newspaper_theme02.less newspaper_temp.less
	lessc newspaper.less > newspaper_theme02.css
	
	
newspaper_theme03:
	cp ../css/newspaper_theme03.less newspaper_temp.less
	lessc newspaper.less > newspaper_theme03.css
	
	
newspaper_theme04:
	cp ../css/newspaper_theme04.less newspaper_temp.less
	lessc newspaper.less > newspaper_theme04.css
	
newspaper_theme05:
	cp ../css/newspaper_theme05.less newspaper_temp.less
	lessc newspaper.less > newspaper_theme05.css
	

geek_theme01:
	cp ../css/geek_theme1.less newspaper_temp.less
	lessc newspaper_temp.less > geek_theme01.css
	
geek_theme06:
	cp ../css/geek_theme6.less newspaper_temp.less
	lessc newspaper_temp.less > geek_theme06.css
	
geek_theme07:
	cp ../css/geek_theme7.less newspaper_temp.less
	lessc newspaper_temp.less > geek_theme07.css